version: "3.7"
services:

  apache:
    container_name: ${APPLICATION_NAME}_webserver
    build:
      context: .
      dockerfile: ./.docker/webserver/Dockerfile
    depends_on:
      - php
    networks:
      - backend
    expose:
      - ${APACHE_PORT}
    ports:
      - ${APACHE_PORT}:80

  php:
    container_name: ${APPLICATION_NAME}_php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      args:
        - APPLICATION_NAME=${APPLICATION_NAME}
        - PHP_VERSION=${PHP_VERSION}
    networks:
      - backend
      - frontend

networks:
  frontend:
  backend:
